include config/base.config
include config/fetch.config

#### llvm
LLVMVER		= 22.1.8
LLVMSRC		= llvm-project-${LLVMVER}.src
LLVMDIR		= ${LLVMSRC}
LLVMTAR		= ${LLVMDIR}.tar.xz
LLVM_INST_PATH	= ${NLYTIQ_INST_PATH}

ifeq (${OS},Darwin)
CMAKE_BIN	= ${NLYTIQ_INST_PATH}/bin/cmake
else
CMAKE_BIN       = $(shell which cmake)
endif

# gcc-9 and later currently fail on build (in Ubuntu 20.04), so use gcc-8 for the moment
GCC		= gcc
GXX		= g++

### libcxx, libcxxabi and libunwind are runtimes, not projects.  They were in
### LLVM_ENABLE_PROJECTS here, which llvm has refused outright since 16:
###
###     libcxx isn't a known project: bolt;clang;clang-tools-extra;
###     compiler-rt;cross-project-tests;libclc;lld;lldb;mlir;openmp;polly;
###     flang;libc.  Did you mean to enable it as a runtime in
###     LLVM_ENABLE_RUNTIMES?
###
### mlir is added because flang does not build without it, and the duplicate
### libcxxabi in the old list is gone.
###
### compiler-rt and openmp moved to the runtimes list as well.  Both are still
### accepted as projects, but building compiler-rt that way while anything else
### is a runtime collides:
###
###     add_custom_target cannot create target "check-builtins" because another
###     target with the same name already exists
###
### flang-rt is new in llvm 21 and is what makes flang a usable Fortran
### compiler rather than just a driver -- without it the configure log says
### "Not building Flang-RT.  For a usable Fortran toolchain ... add
### LLVM_ENABLE_RUNTIMES=flang-rt".
LLVM_PROJECTS	= clang;clang-tools-extra;lld;lldb;polly;mlir;flang;libclc
LLVM_RUNTIMES	= libcxx;libcxxabi;libunwind;compiler-rt;openmp;flang-rt

CMAKE_CMD	= CC=${GCC} CXX=${GXX} ${CMAKE_BIN}  -G "Unix Makefiles" 				\
			-DCMAKE_INSTALL_PREFIX:STRING=${NLYTIQ_INST_PATH} 	\
			-DLLVM_PARALLEL_COMPILE_JOBS:STRING=${NCPU}  		\
			-DLLVM_PARALLEL_LINK_JOBS:STRING=${NCPU}		\
			-DCMAKE_BUILD_TYPE=Release				\
			-DLLVM_ENABLE_PROJECTS="${LLVM_PROJECTS}"		\
			-DLLVM_ENABLE_RUNTIMES="${LLVM_RUNTIMES}"

#                        -DLLVM_ENABLE_CXX1Y:BOOL=On -DLLVM_ENABLE_LTO:BOOL=Off \
#                        -DLLVM_PARALLEL_COMPILE_JOBS:STRING=${NCPU}  \
#                        -DLLVM_PARALLEL_LINK_JOBS:STRING=${NCPU} \
#			-DLLVM_BUILD_LLVM_DYLIB:BOOL=ON \
#			-DLLVM_TARGETS_TO_BUILD:STRING="host" \
#			-DLLVM_LINK_LLVM_DYLIB:BOOL=ON 	\
#			-DLLVM_ENABLE_PROJECTS='clang,clang-tools-extra,lldb,compiler-rt,polly'

BUILDDIR	= ${LLVMDIR}/build

#--------------------------------------------------------------------------#

all:    	install-llvm 

clean:		clean-llvm


configure-llvm: sources/${LLVMTAR}
	tar -Jxf sources/${LLVMTAR}
	mkdir -p ${BUILDDIR}
	touch configure-llvm

make-llvm: configure-llvm
	cd ${BUILDDIR} ; ${CMAKE_CMD} ../llvm
	cd ${BUILDDIR}  ; make -j${NCPU}
	touch make-llvm

install-llvm: make-llvm
	cd ${BUILDDIR}  ; make -j${NCPU} install
ifeq ($(OS),Linux)
	#echo "${NLYTIQ_INST_PATH}/lib" > /etc/ld.so.conf.d/nlytiq.conf
	#ldconfig
endif
	touch install-llvm

clean-llvm:
	rm -rf ${LLVMDIR} make-llvm  install-llvm configure-llvm ${BUILDDIR} 
