include config/base.config

####   
RUSTUPINIT	= sources/rustup-init.sh
#--------------------------------------------------------------------------#

all:    	install-rustbin

clean:		clean-rust  

install-rustbin: ${RUSTUPINIT}
	CARGO_INSTALL_ROOT=${NLYTIQ_INST_PATH} RUSTUP_HOME=${NLYTIQ_INST_PATH} ${RUSTUPINIT} -v -y
	CARGO_INSTALL_ROOT=${NLYTIQ_INST_PATH} RUSTUP_HOME=${NLYTIQ_INST_PATH} ${HOME}/.cargo/bin/rustup update
	touch install-rustbin


clean-rust:
	rm -rf install-rustbin
