include base.config

####   
PCREVER		= 10.31
PCRE		= pcre2-${PCREVER}
PCRE_INST_PATH	= ${NLYTIQ_INST_PATH}


# ${_EPF_} contains the front matter for configure after the include below
include configure.prefix.flag.config

#--------------------------------------------------------------------------#

all:    	install-pcre

clean:		clean-pcre

configure-pcre:	
	tar -zxvf sources/${PCRE}.tar.gz
	cd ${PCRE} ; ${_EPF_} ./configure --prefix=${NLYTIQ_INST_PATH} 
	touch configure-pcre

make-pcre: configure-pcre
	cd ${PCRE} ;  make -j${NCPU}
	touch make-pcre

install-pcre: make-pcre
	cd ${PCRE} ;   make install
	touch install-pcre

clean-pcre:
	rm -rf ${PCRE} make-pcre configure-pcre install-pcre 
