include base.config

####   
PCREVER		= 10.23
PCRE		= pcre2-${PCREVER}
PCRE_INST_PATH	= ${NLYTIQ_INST_PATH}

### force baseline gcc if GCC_VER is not blank
include forcegcc.config


#--------------------------------------------------------------------------#

all:    	install-pcre

clean:		clean-pcre

configure-pcre:	
	tar -zxvf sources/${PCRE}.tar.gz
	cd ${PCRE} ; export CC=${CC} CXX=${CXX} CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}" ; ./configure --prefix=${NLYTIQ_INST_PATH} 
	touch configure-pcre

make-pcre: configure-pcre
	cd ${PCRE} ; export CC=${CC} CXX=${CXX} CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}"  LDFLAGS="${LDFLAGS}"  ; make -j${NCPU}
	touch make-pcre

install-pcre: make-pcre
	cd ${PCRE} ;  export CC=${CC} CXX=${CXX} CFLAGS="${CFLAGS}" CXXFLAGS="${CXXFLAGS}" LDFLAGS="${LDFLAGS}" ;  make install
	touch install-pcre

clean-pcre:
	rm -rf ${PCRE} make-pcre configure-pcre install-pcre 
