include config/base.config
include config/fetch.config

####
maximaVER	= 5.49.0
maxima		= maxima-${maximaVER}
maximaTAR	= ${maxima}.tar.gz
DIR		= $(shell pwd)/${maxima}


# ${_EPF_} contains the front matter for configure after the include below
include config/configure.prefix.flag.config


#--------------------------------------------------------------------------#

all:    	install-quicklisp

clean:		clean-maxima

# assume SBCL, as this is available in most distros.  You
# might need to build from the latest SBCL source at
# https://sourceforge.net/projects/sbcl/files/sbcl/

### maxima's configure runs 'git describe' and uses the answer as its version,
### on the assumption that git fails for an unpacked tarball.  Here the tarball
### is unpacked inside this repository, so git answers with *this* tree's
### description: after the v0.75 tag was created, maxima built itself as
### version "v0.75_dirty" and installed into lib/maxima/v0.75_dirty/ instead of
### lib/maxima/5.49.0/.  Pointing GIT_DIR at nothing restores the behaviour
### configure.ac is expecting, which is to keep the tarball's own version.
_NOGIT_	= GIT_DIR=/nonexistent

configure-maxima:	 sources/${maximaTAR}
	tar -zxvf sources/${maximaTAR}
	cd ${DIR} ; ${_NOGIT_} ${_EPF_} ./configure --prefix=${NLYTIQ_INST_PATH} \
		--enable-mathjax \
		--enable-sbcl 	\
		--enable-sbcl-exec
	touch configure-maxima

make-maxima: configure-maxima
	cd ${DIR} ; export  LD_LIBRARY_PATH=${DIR} ;  make -j${NCPU}
	touch make-maxima

install-maxima: make-maxima
	cd ${DIR} ; export  LD_LIBRARY_PATH=${DIR} ; make install
	touch install-maxima

install-quicklisp: install-maxima
	cd sources ; ./maxima-install-quicklisp.max
	touch install-quicklisp


clean-maxima:
	rm -rf ${DIR} make-maxima configure-maxima install-maxima \
		${DIR} install-quicklisp
