include base.config

####   
RUSTUPINIT	= sources/rustup-init
#--------------------------------------------------------------------------#

all:    	install-rustbin

clean:		clean-rust  

install-rustbin: sources/${RUSTBINTAR}
	export RUSTUP_HOME=${NLYTIQ_INST_PATH} ; ${RUSTUPINIT} -v
	touch install-rustbin


clean-rust:
	rm -rf install-rustbin
